### ISSUE TITLE
One Side Camera is black when using XR interaction Toolkit

### ISSUE THREAD

**Issue by ragavendranbala** [ZibraAI/com.zibra.liquids-free#1]
Unity Version : 2020.3.17f1

Steps to Reproduce:
Create Project with URP
Install XR interaction toolkit
Run Demo Scene with Zibra liquid
Check with VR headsets. 

The liquids can't be seen on the Scene and only one side camera is rendering.

**Comment by alex-puchka** [comment]
We are currently do not support VR, but in future we will do it. Join discord channel for most recent updates https://discord.gg/3hSqeCcDTp
